controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        en: '' # don't prefix URLs for English, the default locale
        ru: '/ru'
kernel:
    resource: ../../src/Kernel.php
    type: annotation
